package com.healthfinance.notificationservice.model;

public enum NotificationType {
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLATION,
    PRESCRIPTION_READY,
    PRESCRIPTION_REFILL_REMINDER,
    MEDICAL_REPORT_AVAILABLE,
    INVOICE_GENERATED,
    PAYMENT_RECEIVED,
    PAYMENT_REMINDER,
    INSURANCE_CLAIM_UPDATE,
    GENERAL_NOTIFICATION
}
